### ISSUE TITLE
AttributeError: Method CustomizedVideoInput is not a registered operator. Did you mean: []

### ISSUE THREAD

**Issue by kellycvcv** [facebookresearch/video-nonlocal-net#12]
Hi,
    Sorry to truble you again,and I have  a new problem:
    "AttributeError: Method CustomizedVideoInput is not a registered operator. Did you mean: []"

**Comment by xuchao1688** [comment]
You should set the cmake flag to `USE_FFMPEG ON` in `~/caffe2/CMakeLists.txt`. Because you put the customized ops in `~/caffe2/caffe2/video` folder which will be omitted while compiling if `USE_FFMPEG OFF`.  To prove that, you also can read the `CMakeList.txt` in `video-nonlocal-net\caffe2_customized_ops\video`

**Comment by kellycvcv** [comment]
Hi，
That works well!
But I meet a new problem:"Insufficient data to determine video format".
Can you tell how to make my dataset?
The video format is H264,is it right?

**Comment by kellycvcv** [comment]
Dear xiaolong,
Thank you for your awnser,and I try the video'fps>=32,it's perfectly ok!But my video almost less than 32fps,I try your way:int probeSz = 4 * 1024 + AVPROBE_PADDING_SIZE ,and recompile sucessful, but also can't fix the video less than 32fps.
Did I miss something to change?
Wait for your watch!

**Comment by xiaolonw** [comment]
Hi,
It has nothing to do with fps. It is related to the total number of frames in the videos. 
How many frames are there in your short video?
You might try to make probeSz even smaller to 
probeSz = 1 * 1024 + AVPROBE_PADDING_SIZE
